#Data Preprocessing

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
data = pd.read_csv('/content/datasets_4458_8204_winequality-red (3).csv')

In [ ]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [ ]:
data['quality'].unique()

array([5, 6, 7, 4, 8, 3])

#Separate Features and Target

* Here lets considering 'quality' as target
*  and rest of the columns as features

In [ ]:
x = data.iloc[:,:-1].values
y = data.iloc[:, -1].values

In [ ]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [ ]:
y

array([5, 5, 5, ..., 6, 5, 6])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [ ]:
y_train

array([7, 5, 6, ..., 6, 6, 5])

In [ ]:
y_test

array([6, 6, 5, 4, 6, 5, 6, 7, 6, 6, 5, 5, 6, 5, 7, 5, 6, 6, 6, 5, 4, 6,
       5, 6, 6, 6, 5, 6, 6, 5, 6, 6, 7, 8, 6, 4, 6, 6, 5, 6, 5, 5, 7, 5,
       5, 5, 7, 7, 6, 7, 5, 4, 5, 8, 5, 5, 6, 5, 5, 4, 6, 5, 5, 7, 6, 6,
       6, 8, 5, 5, 5, 6, 7, 6, 5, 5, 5, 6, 6, 6, 5, 7, 6, 5, 7, 5, 7, 5,
       7, 6, 6, 6, 5, 6, 5, 5, 6, 5, 5, 5, 6, 5, 6, 6, 4, 6, 6, 5, 6, 5,
       6, 6, 5, 6, 7, 6, 6, 5, 7, 5, 6, 6, 5, 6, 5, 5, 6, 5, 5, 6, 4, 5,
       5, 5, 5, 7, 5, 5, 5, 5, 6, 6, 6, 5, 6, 6, 6, 7, 6, 7, 5, 6, 6, 6,
       6, 5, 6, 6, 6, 5, 6, 6, 5, 6, 6, 8, 5, 7, 7, 5, 6, 5, 6, 6, 5, 7,
       5, 5, 7, 5, 6, 7, 5, 6, 5, 5, 6, 6, 7, 5, 6, 5, 5, 6, 5, 6, 5, 5,
       5, 5, 6, 5, 6, 6, 7, 6, 5, 6, 6, 6, 7, 7, 5, 5, 5, 6, 4, 5, 4, 5,
       6, 7, 7, 5, 5, 5, 6, 6, 7, 6, 6, 5, 5, 6, 5, 5, 5, 5, 6, 6, 6, 7,
       5, 7, 5, 5, 5, 7, 5, 6, 5, 5, 5, 5, 6, 6, 6, 5, 6, 6, 5, 5, 5, 5,
       6, 5, 5, 6, 6, 6, 6, 5, 6, 6, 6, 7, 6, 6, 6, 5, 6, 6, 5, 5, 5, 5,
       6, 6, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 7,

In [ ]:
x_train

array([[ 9.2 ,  0.31,  0.36, ...,  3.33,  0.86, 12.  ],
       [ 7.8 ,  0.56,  0.19, ...,  3.33,  0.54,  9.5 ],
       [ 8.8 ,  0.48,  0.41, ...,  3.31,  0.53, 10.5 ],
       ...,
       [ 8.6 ,  0.53,  0.22, ...,  3.2 ,  0.56, 10.2 ],
       [ 7.7 ,  0.43,  0.25, ...,  3.37,  0.58, 10.5 ],
       [ 6.8 ,  0.66,  0.07, ...,  3.29,  0.6 ,  9.3 ]])

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
ntrain = y_train.reshape(len(y_train), 1)
ntest = y_test.reshape(len(y_test), 1)

In [ ]:
ntrain

array([[7],
       [5],
       [6],
       ...,
       [6],
       [6],
       [5]])

In [ ]:

ntest

array([[6],
       [6],
       [5],
       [4],
       [6],
       [5],
       [6],
       [7],
       [6],
       [6],
       [5],
       [5],
       [6],
       [5],
       [7],
       [5],
       [6],
       [6],
       [6],
       [5],
       [4],
       [6],
       [5],
       [6],
       [6],
       [6],
       [5],
       [6],
       [6],
       [5],
       [6],
       [6],
       [7],
       [8],
       [6],
       [4],
       [6],
       [6],
       [5],
       [6],
       [5],
       [5],
       [7],
       [5],
       [5],
       [5],
       [7],
       [7],
       [6],
       [7],
       [5],
       [4],
       [5],
       [8],
       [5],
       [5],
       [6],
       [5],
       [5],
       [4],
       [6],
       [5],
       [5],
       [7],
       [6],
       [6],
       [6],
       [8],
       [5],
       [5],
       [5],
       [6],
       [7],
       [6],
       [5],
       [5],
       [5],
       [6],
       [6],
       [6],
       [5],
       [7],
       [6],
    

In [ ]:
x_sc = StandardScaler()
y_sc = StandardScaler()

In [ ]:
xn_train = x_sc.fit_transform(x_train)
yn_train = y_sc.fit_transform(ntrain)

In [ ]:
xn_test = x_sc.transform(x_test)
yn_test = y_sc.transform(ntest)

In [ ]:
xn_train

array([[ 0.5057257 , -1.22637962,  0.46455418, ...,  0.12579779,
         1.25420611,  1.48053894],
       [-0.2931032 ,  0.17290272, -0.40763315, ...,  0.12579779,
        -0.69462258, -0.85967722],
       [ 0.27748887, -0.27486763,  0.72107986, ..., -0.00390424,
        -0.75552347,  0.07640925],
       ...,
       [ 0.16337046,  0.00498884, -0.25371774, ..., -0.71726545,
        -0.57282078, -0.20441669],
       [-0.35016241, -0.5547241 , -0.09980233, ...,  0.38520187,
        -0.45101899,  0.07640925],
       [-0.86369527,  0.73261566, -1.0232948 , ..., -0.13360628,
        -0.3292172 , -1.04689451]])

In [ ]:
xn_test

array([[ 1.19043619, -0.5547241 ,  1.1828261 , ..., -1.36577565,
         1.315107  ,  0.91888706],
       [ 0.56278491, -0.77860927,  0.66977473, ...,  0.19064881,
         0.58429625, -0.20441669],
       [-0.57839923,  0.3408166 , -0.04849719, ..., -0.1984573 ,
        -0.81642437, -0.48524263],
       ...,
       [ 1.41867301, -0.44278151,  0.31063877, ..., -0.45786138,
         0.34069266,  0.35723519],
       [ 0.33454808,  0.45275919,  1.13152096, ..., -1.23607361,
         2.22862045, -1.04689451],
       [-1.32016893, -0.16292504, -1.38243076, ...,  0.32035085,
        -1.24273065, -0.85967722]])

In [ ]:
yn_train

array([[ 1.68463147],
       [-0.76243684],
       [ 0.46109731],
       ...,
       [ 0.46109731],
       [ 0.46109731],
       [-0.76243684]])

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
r_reg = RandomForestRegressor()
l_reg = LinearRegression()
d_reg = DecisionTreeRegressor()
s_reg = SVR()
p_reg = LinearRegression()

In [ ]:
x_pol = PolynomialFeatures(degree=1)
x_pol = x_pol.fit_transform(xn_train)

In [ ]:
temp = PolynomialFeatures(degree=1)
temp = temp.fit_transform(xn_test)

In [ ]:
r_reg.fit(xn_train, yn_train)
l_reg.fit(xn_train, yn_train)
d_reg.fit(xn_train, yn_train)
s_reg.fit(xn_train, yn_train)
p_reg.fit(x_pol, yn_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
r_pred = r_reg.predict(xn_test)
l_pred = l_reg.predict(xn_test)
d_pred = d_reg.predict(xn_test)
s_pred = s_reg.predict(xn_test)
p_pred = p_reg.predict(temp)

In [ ]:

from sklearn.metrics import r2_score

In [ ]:
r = r2_score(yn_test, r_pred)
l = r2_score(yn_test, l_pred)
d = r2_score(yn_test, d_pred)
s = r2_score(yn_test, s_pred)
p = r2_score(yn_test, p_pred)

In [ ]:
print(r, l, d, s, p)

0.47946345381526123 0.32471627739241005 -0.028112449799196693 0.431755804624276 0.32471627739241027
